spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager?characterEncoding=utf-8
    username: root
    password: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
